INSERT INTO REF.Currency (currencyCode, currencySymbol, currencyName, countryName) VALUES
( 'XUA', 'XUA', 'ADB Unit of Account', 'None'),
( 'AFA', '؋', 'Afghanistan Afghani', 'Afghanistan'),
( 'AFN', 'AL', 'Afghanistan Afghani', 'Afghanistan'),
( 'ALL', 'AL', 'Albanian Lek', 'Albania'),
( 'DZD', 'د.ج', 'Algerian Dinar', 'Algeria'),
( 'ADF', '₣', 'Andorran Franc', 'Andorra'),
( 'ADP', '₧', 'Andorran Peseta', 'Andorra'),
( 'AOA', 'Kz', 'Angolan Kwanza', 'Angola'),
( 'AOR', 'Kz', 'Angolan Kwanza Rejustado', 'Angola'),
( 'AON', 'Kz', 'Angolan New Kwanza', 'Angola'),
( 'ARS', 'AR$', 'Argentine Peso', 'Argentina'),
( 'AMD', 'դր.', 'Armenian Dram', 'Armenia'),
( 'AWG', 'Afl', 'Aruban Florin', 'Aruba'),
( 'AUD', 'A$', 'Australian Dollar', 'Australia'),
( 'ATS', 'AU$', 'Austrian Schilling', 'Austria'),
( 'AZM', 'm', 'Azerbaijan Manat', 'Azerbaijan'),
( 'AZN', 'm', 'Azerbaijan New Manat', 'Azerbaijan'),
( 'BSD', 'B$', 'Bahamian Dollar', 'Bahamas'),
( 'BHD', '.د.ب', 'Bahraini Dinar', 'Bahrain'),
( 'BDT', '৳', 'Bangladeshi Taka', 'Bangladesh'),
( 'BBD', 'B$', 'Barbados Dollar', 'Barbados'),
( 'BYR', 'Br', 'Belarusian Ruble', 'Belarus'),
( 'BEF', 'fr', 'Belgian Franc', 'Belgium'),
( 'BZD', 'BZ$', 'Belize Dollar', 'Belize'),
( 'BMD', 'BM$', 'Bermudian Dollar', 'Bermuda'),
( 'BTN', 'Nu.', 'Bhutan Ngultrum', 'Bhutan'),
( 'BOB', 'Bs.', 'Bolivian Boliviano', 'Bolivia'),
( 'BOV', 'BOV', 'Bolivian Mvdol', 'Bolivia'),
( 'BAM', 'KM', 'Bosnian Mark', 'Bosnia'),
( 'BWP', 'BP', 'Botswana Pula', 'Botswana'),
( 'BRL', 'R$', 'Brazilian Real', 'Brazil'),
( 'GBP', '£', 'British Pound', 'United Kingdom'),
( 'BND', 'BN$', 'Brunei Dollar', 'Brunei'),
( 'BGL', 'лв', 'Bulgarian Lev', 'Bulgaria'),
( 'BGN', 'лв', 'Bulgarian Lev', 'Bulgaria'),
( 'BIF', 'BFr', 'Burundi Franc', 'Burundi '),
( 'KHR', '៛', 'Cambodian Riel', 'Cambodia'),
( 'CAD', 'CA$', 'Canadian Dollar', 'Canada'),
( 'CVE', 'Esc', 'Cape Verde Escudo', 'Cape Verde'),
( 'KYD', 'CI$', 'Cayman Islands Dollar', 'Cayman Islands'),
( 'XOF', 'XOFr', 'CFA Franc BCEAO', 'None'),
( 'XAF', 'XAFr', 'CFA Franc BEAC', 'None'),
( 'XPF', 'XPFr', 'CFP Franc', 'None'),
( 'CLP', 'CL$', 'Chilean Peso', 'Chile'),
( 'CLF', 'CL$', 'Chilean Unidad de Fomento', 'Chile'),
( 'CNY', '元', 'Chinese Yuan Renminbi', 'China'),
( 'COP', 'CO$', 'Colombian Peso', 'Colombia'),
( 'KMF', 'KFr', 'Comoros Franc', 'Comoros'),
( 'CDF', 'CDFr', 'Congolese Franc', 'Congo'),
( 'CRC', 'C₡', 'Costa Rican Colon', 'Costa Rica'),
( 'HRK', 'kn', 'Croatian Kuna', 'Croatian'),
( 'CUC', 'CUC$', 'Cuban Convertible Peso', 'Cuba'),
( 'CUP', '$MN', 'Cuban Peso', 'Cuba'),
( 'CYP', 'CY£', 'Cyprus Pound', 'Cyprus'),
( 'CZK', 'Kč', 'Czech Koruna', 'Czechoslovakia'),
( 'DKK', 'Dkr', 'Danish Krone', 'Denmark'),
( 'DJF', 'DFr', 'Djibouti Franc', 'Djibouti'),
( 'DOP', 'RD$', 'Dominican R. Peso', 'Dominican Republic'),
( 'NLG', 'ƒ', 'Dutch Guilder', 'Netherlands'),
( 'XCD', 'EC$', 'East Caribbean Dollar', 'None'),
( 'ECS', 'S/', 'Ecuador Sucre', 'Ecuador'),
( 'EGP', 'EG£', 'Egyptian Pound', 'Egypt'),
( 'SVC', 'S₡', 'El Salvador Colon', 'El Salvadore'),
( 'ERN', 'Nfk', 'Eritrean Nakfa', 'Eritrea'),
( 'EEK', 'kr', 'Estonian Kroon', 'Estonia'),
( 'ETB', 'Br', 'Ethiopian Birr', 'Ethiopia'),
( 'EUR', '€', 'Euro', 'Euro'),
( 'XBA', 'XBA', 'European Composite Unit', 'None'),
( 'XEU', 'ECU', 'European Currency Unit', 'None'),
( 'XBB', 'XBB', 'European Monetary Unit', 'None'),
( 'XBD', 'XBD', 'European Unit of Account 17', 'None'),
( 'XBC', 'XBC', 'European Unit of Account 9', 'None'),
( 'FKP', '£', 'Falkland Islands Pound', 'Falkland Islands'),
( 'FJD', 'FJ$', 'Fiji Dollar', 'Fiji'),
( 'FIM', 'mk', 'Finnish Markka', 'Finland'),
( 'FRF', '₣', 'French Franc', 'France'),
( 'GMD', 'D', 'Gambian Dalasi', 'Gambia'),
( 'GEL', 'ლ', 'Georgian Lari', 'Georgia'),
( 'DEM', 'DM', 'German Mark', 'Germany'),
( 'GHC', '₵', 'Ghanaian Cedi', 'Ghana'),
( 'GHS', 'GH¢', 'Ghanaian New Cedi', 'Ghana'),
( 'GIP', '£', 'Gibraltar Pound', 'Gibraltar'),
( 'XAU', 'XAU', 'Gold (oz.)', 'None'),
( 'GRD', 'Δρ', 'Greek Drachma', 'Greece'),
( 'GTQ', 'Q', 'Guatemalan Quetzal', 'Guatemala'),
( 'GGP', '£', 'Guernsey Pound', 'Guernsey '),
( 'GNF', 'GFr', 'Guinea Franc', 'Guinea'),
( 'GYD', 'GY$', 'Guyanese Dollar', 'Guyana'),
( 'HTG', 'G', 'Haitian Gourde', 'Haiti'),
( 'HNL', 'HL', 'Honduran Lempira', 'Honduras'),
( 'HKD', 'HK$', 'Hong Kong Dollar', 'Hong Kong'),
( 'HUF', 'Ft', 'Hungarian Forint', 'Hungary'),
( 'ISK', 'Ikr', 'Iceland Krona', 'Iceland'),
( 'XDR', 'XDR', 'IMF Special Drawing Rights', 'None'),
( 'INR', '₨', 'Indian Rupee', 'India'),
( 'IDR', 'Rp', 'Indonesian Rupiah', 'Indonesia'),
( 'IRR', '﷼I', 'Iranian Rial', 'Iran'),
( 'IQD', 'ع.د', 'Iraqi Dinar', 'Iraq'),
( 'IEP', '£', 'Irish Punt', 'Ireland'),
( 'IMP', '£', 'Isle of Man Pound', 'Isle of Man'),
( 'ILS', '₪', 'Israeli New Shekel', 'Israel'),
( 'ITL', '₤', 'Italian Lira', 'Italy'),
( 'JMD', 'JM$', 'Jamaican Dollar', 'Jamaica'),
( 'JPY', '¥', 'Japanese Yen', 'Japan'),
( 'JEP', '£', 'Jersey Pound', 'Jersey'),
( 'JOD', 'د.ا', 'Jordanian Dinar', 'Jordan'),
( 'KZT', '₸', 'Kazakhstan Tenge', 'Kazakhstan'),
( 'KES', 'KSh', 'Kenyan Shilling', 'Kenya'),
( 'KWD', 'د.ك', 'Kuwaiti Dinar', 'Kuwaiti Dinar'),
( 'KGS', 'KSom', 'Kyrgyzstanian Som', 'Kyrgyzstan'),
( 'LAK', '₭', 'Lao Kip', 'Laos'),
( 'LVL', 'Ls', 'Latvian Lats', 'Latvia'),
( 'LBP', 'ل.ل', 'Lebanese Pound', 'Lebanon'),
( 'LSL', 'LL', 'Lesotho Loti', 'Lesotho'),
( 'LRD', 'LR$', 'Liberian Dollar', 'Liberia'),
( 'LYD', 'ل.د', 'Libyan Dinar', 'Libya'),
( 'LTL', 'Lt', 'Lithuanian Litas', 'Lithuania'),
( 'LUF', 'F', 'Luxembourg Franc', 'Luxembourg'),
( 'MOP', 'MOP$', 'Macau Pataca', 'Macau'),
( 'MKD', 'ден', 'Macedonian Denar', 'Macedoniar'),
( 'MGA', 'Ar', 'Malagasy Ariary', 'Madagascar'),
( 'MGF', 'MGF', 'Malagasy Franc', 'Madagascar'),
( 'MWK', 'MK', 'Malawi Kwacha', 'Malawi'),
( 'MYR', 'RM', 'Malaysian Ringgit', 'Malaysia'),
( 'MVR', '.ރ', 'Maldive Rufiyaa', 'Maldives'),
( 'MTL', 'Lm', 'Maltese Lira', 'Malta'),
( 'MRO', 'UM', 'Mauritanian Ouguiya', 'Mauritania'),
( 'MUR', 'M₨', 'Mauritius Rupee', 'Mauritius'),
( 'MXN', 'MX$', 'Mexican Peso', 'Mexico'),
( 'MXP', 'MX$', 'Mexican Peso ', 'Mexico '),
( 'MXV', 'MXV', 'Mexican Unidad de Inversion', 'Mexico'),
( 'MDL', 'ML', 'Moldovan Leu', 'Moldova'),
( 'MNT', '₮', 'Mongolian Tugrik', 'Mongolia'),
( 'MAD', 'د.م.', 'Moroccan Dirham', 'Morocco'),
( 'MZM', 'MT', 'Mozambique Metical', 'Mozambique'),
( 'MZN', 'MT', 'Mozambique New Metical', 'Mozambique '),
( 'MMK', 'Ks', 'Myanmar Kyat', 'Myanmar'),
( 'NAD', 'NA$', 'Namibia Dollar', 'Namibia'),
( 'NPR', 'N₨', 'Nepalese Rupee', 'Nepal'),
( 'NZD', 'NZ$', 'New Zealand Dollar', 'New Zealand'),
( 'NIO', 'C$', 'Nicaraguan Cordoba Oro', 'Nicaragua'),
( 'NGN', '₦', 'Nigerian Naira', 'Nigeria'),
( 'ANG', 'ƒ', 'NL Antillian Guilder', 'Curacao '),
( 'XXX', 'XXX', 'No Currency', 'None'),
( 'KPW', 'N₩', 'North Korean Won', 'North Korea'),
( 'NOK', 'Nkr', 'Norwegian Kroner', 'Norway'),
( 'OMR', 'ر.ع.', 'Omani Rial', 'Oman'),
( 'PKR', 'P₨', 'Pakistan Rupee', 'Pakistan'),
( 'XPD', 'XPD', 'Palladium (oz.)', 'None'),
( 'PAB', 'B/.', 'Panamanian Balboa', 'Panama'),
( 'PGK', 'K', 'Papua New Guinea Kina', 'Papua New Guinea'),
( 'PYG', '₲', 'Paraguay Guarani', 'Paraguay'),
( 'PEN', 'S/.', 'Peruvian Nuevo Sol', 'Peru'),
( 'PHP', '₱', 'Philippine Peso', 'Philippines'),
( 'XPT', 'XPT', 'Platinum (oz.)', 'None'),
( 'PLN', 'zł', 'Polish Zloty', 'Poland'),
( 'PTE', 'PT$', 'Portuguese Escudo', 'Portugal'),
( 'QAR', 'ر.ق', 'Qatari Rial', 'Qatar'),
( 'ROL', 'leu', 'Romanian Lei', 'Romania'),
( 'RON', 'RL', 'Romanian New Lei', 'Romania'),
( 'RUB', 'р.', 'Russian Rouble', 'Russia'),
( 'RWF', 'RFr', 'Rwandan Franc', 'Rwanda'),
( 'WST', 'T', 'Samoan Tala', 'Samoa'),
( 'STD', 'Db', 'Sao Tome/Principe Dobra', 'Sao Tome and Principe'),
( 'SAR', 'ر.س', 'Saudi Riyal', 'Saudi Arabia'),
( 'SPL', 'SPL', 'Seborgan Luigino', 'Seborga'),
( 'RSD', 'РСД', 'Serbian Dinar', 'Serbia'),
( 'SCR', 'S₨', 'Seychelles Rupee', 'Seychelles'),
( 'SLL', 'Le', 'Sierra Leone Leone', 'Sierra Leone'),
( 'XAG', 'XAG', 'Silver (oz.)', 'None'),
( 'SGD', 'SG$', 'Singapore Dollar', 'Singapore'),
( 'SKK', 'Sk', 'Slovak Koruna', 'Slovakia'),
( 'SIT', 'SIT', 'Slovenian Tolar', 'Slovenia'),
( 'SBD', 'SB$', 'Solomon Islands Dollar', 'Solomon Islands'),
( 'SOS', 'SSh', 'Somali Shilling', 'Somalia'),
( 'ZAR', 'R', 'South African Rand', 'South Africa'),
( 'KRW', 'S₩', 'South Korean Won', 'South Korean'),
( 'SSP', 'SS£', 'South Sudonese Pound', 'South Sudan'),
( 'ESP', '₧', 'Spanish Peseta', 'Spain'),
( 'LKR', 'Rs', 'Sri Lanka Rupee', 'Sri Lanka'),
( 'SHP', '£', 'St. Helena Pound', 'St. Helena'),
( 'XSU', 'XSU', 'SUCRE', 'None'),
( 'SDD', 'SU£', 'Sudanese Dinar', 'Sudan'),
( 'SDP', 'SDP', 'Sudanese Old Pound', 'Sudan'),
( 'SDG', 'junaih', 'Sudanese Pound', 'Sudan'),
( 'SRD', 'SR$', 'Suriname Dollar', 'Suriname'),
( 'SRG', 'SU$', 'Suriname Guilder', 'Suriname'),
( 'SZL', 'SL', 'Swaziland Lilangeni', 'Swaziland'),
( 'SEK', 'Skr', 'Swedish Krona', 'Sweden'),
( 'CHF', 'CHFr', 'Swiss Franc', 'Switzerland'),
( 'CHE', 'CHE', 'Swiss WIR Euro', 'Switzerland'),
( 'CHW', 'CHW', 'Swiss WIR Franc', 'Switzerland'),
( 'SYP', 'SY£', 'Syrian Pound', 'Syria'),
( 'TWD', 'TW$', 'Taiwan Dollar', 'Taiwan'),
( 'TJS', 'ЅМ', 'Tajikistani Somoni', 'Tajikistan'),
( 'TZS', 'TSh', 'Tanzanian Shilling', 'Tanzania'),
( 'XTS', 'XTS', 'Testing code', 'None'),
( 'THB', '฿', 'Thai Baht', 'Thailand'),
( 'TOP', 'T$', 'Tonga Paanga', 'Tonga'),
( 'TTD', 'TT$', 'Trinidad/Tobago Dollar', 'Trinidad and Tobago'),
( 'TND', 'د.ت', 'Tunisian Dinar', 'Tunisia'),
( 'TRY', 'TL', 'Turkish Lira', 'Turkey'),
( 'TRL', 'TL', 'Turkish Old Lira', 'Turkey'),
( 'TMM', 'm', 'Turkmenistan Manat', 'Turkmenistan'),
( 'TMT', 'm', 'Turkmenistan New Manat', 'Turkmenistan'),
( 'TVD', '$TU', 'Tuvaluan Dollar', 'Tuvalu'),
( 'UGX', 'Ush', 'Uganda Shilling', 'Uganda'),
( 'UAH', '₴', 'Ukraine Hryvnia', 'Ukraine'),
( 'COU', 'COU', 'Unidad de Valor Real ', 'Colombia'),
( 'UYI', 'U$', 'Uruguay Peso en Unidades', 'Uruguay'),
( 'UYU', 'UY$', 'Uruguayan Peso', 'Uruguay'),
( 'USD', '$', 'US Dollar', 'United States'),
( 'USN', '$', 'US Dollar Next Day', 'United States'),
( 'USS', '$', 'US Dollar Same Day', 'United States'),
( 'UD1', 'U1', 'User Defined 1', 'User Defined 1'),
( 'UD2', 'U2', 'User Defined 2', 'User Defined 2'),
( 'UD3', 'U3', 'User Defined 3', 'User Defined 3'),
( 'UD4', 'U4', 'User Defined 4', 'User Defined 4'),
( 'UD5', 'U5', 'User Defined 5', 'User Defined 5'),
( 'AED', 'د.إ', 'Utd. Arab Emir. Dirham', 'United Arab Emirates'),
( 'UZS', 'Usom', 'Uzbekistan Som', 'Uzbekistan'),
( 'VUV', 'Vt', 'Vanuatu Vatu', 'Vanuatu'),
( 'VEB', 'Bs F', 'Venezuelan Bolivar', 'Venezuela'),
( 'VEF', 'Bs F', 'Venezuelan Bolivar Fuerte', 'Venezuela'),
( 'VND', '₫', 'Vietnamese Dong', 'Vietnam'),
( 'YER', '﷼Y', 'Yemeni Rial', 'Yemen'),
( 'YUN', 'YUN', 'Yugoslav Dinar', 'Yugoslavia'),
( 'ZMK', 'ZK', 'Zambian Kwacha', 'Zambia'),
( 'ZMW', 'ZK', 'Zambian Kwacha', 'Zambia'),
( 'ZWD', 'ZW$', 'Zimbabwe Dollar', 'Zimbabwe'),
( 'ZWL', 'Z$', 'Zimbabwe Old Dollar ', 'Zimbabwe ')
;
