INSERT INTO REF.Country (countryGeoId, countryCode, countryName, iso2a, iso3a, iso3n, fips, countryModelCode, countryModelName) VALUES
    (533, 'AA', 'Aruba', 'AW', 'ABW', '533', 'AA', 'CB', 'Caribbean'),
    (28, 'AC', 'Antigua and Barbuda', 'AG', 'ATG', '28', 'AC', 'CB', 'Caribbean'),
    (784, 'AE', 'United Arab Emirates', 'AE', 'ARE', '784', 'AE', 'AE', 'United Arab Emirates'),
    (4, 'AF', 'Afghanistan', 'AF', 'AFG', '4', 'AF', 'AF', 'Afghanistan'),
    (12, 'AG', 'Algeria', 'DZ', 'DZA', '12', 'AG', 'DZ', 'Algeria'),
    (31, 'AJ', 'Azerbaijan', 'AZ', 'AZE', '31', 'AJ', 'AZ', 'Azerbaijan'),
    (8, 'AL', 'Albania', 'AL', 'ALB', '8', 'AL', 'AL', 'Albania'),
    (51, 'AM', 'Armenia', 'AM', 'ARM', '51', 'AM', 'AM', 'Armenia'),
    (20, 'AN', 'Andorra', 'AD', 'AND', '20', 'AN', 'AD', 'Andorra'),
    (24, 'AO', 'Angola', 'AO', 'AGO', '24', 'AO', 'AO', 'Angola'),
    (16, 'AQ', 'American Samoa', 'AS', 'ASM', '16', 'AQ', 'AS', 'American Samoa'),
    (32, 'AR', 'Argentina', 'AR', 'ARG', '32', 'AR', 'AR', 'Argentina'),
    (36, 'AS', 'Australia', 'AU', 'AUS', '36', 'AS', 'AU', 'Australia'),
    (969, 'AT', 'Ashmore and Cartier Islands', '', '', '969', 'AT', '', 'Ashmore and Cartier Islands'),
    (40, 'AU', 'Austria', 'AT', 'AUT', '40', 'AU', 'AT', 'Austria'),
    (660, 'AV', 'Anguilla', 'AI', 'AIA', '660', 'AV', 'CB', 'Caribbean'),
    (10, 'AY', 'Antarctica', 'AQ', 'ATA', '10', 'AY', 'AQ', 'Antarctica'),
    (48, 'BA', 'Bahrain', 'BH', 'BHR', '48', 'BA', 'BH', 'Bahrain'),
    (52, 'BB', 'Barbados', 'BB', 'BRB', '52', 'BB', 'CB', 'Caribbean'),
    (72, 'BC', 'Botswana', 'BW', 'BWA', '72', 'BC', 'BW', 'Botswana'),
    (60, 'BD', 'Bermuda', 'BM', 'BMU', '60', 'BD', 'CB', 'Caribbean'),
    (56, 'BE', 'Belgium', 'BE', 'BEL', '56', 'BE', 'BE', 'Belgium'),
    (44, 'BF', 'Bahamas', 'BS', 'BHS', '44', 'BF', 'CB', 'Caribbean'),
    (50, 'BG', 'Bangladesh', 'BD', 'BGD', '50', 'BG', 'BD', 'Bangladesh'),
    (84, 'BH', 'Belize', 'BZ', 'BLZ', '84', 'BH', 'BZ', 'Belize'),
    (70, 'BK', 'Bosnia And Herzegovina', 'BA', 'BIH', '70', 'BK', 'BA', 'Bosnia And Herzegovina'),
    (68, 'BL', 'Bolivia', 'BO', 'BOL', '68', 'BL', 'BO', 'Bolivia'),
    (104, 'BM', 'Myanmar', 'MM', 'MMR', '104', 'BM', 'MM', 'Myanmar'),
    (204, 'BN', 'Benin', 'BJ', 'BEN', '204', 'BN', 'BJ', 'Benin'),
    (112, 'BO', 'Belarus', 'BY', 'BLR', '112', 'BO', 'BY', 'Belarus'),
    (90, 'BP', 'Solomon Islands', 'SB', 'SLB', '90', 'BP', 'SB', 'Solomon Islands'),
    (980, 'BQ', 'Navassa Island', '', '', '980', 'BQ', '', 'Navassa Island'),
    (76, 'BR', 'Brazil', 'BR', 'BRA', '76', 'BR', 'BR', 'Brazil'),
    (998, 'BS', 'Bassas da India', '', '', '998', 'BS', '', 'Bassas da India'),
    (64, 'BT', 'Bhutan', 'BT', 'BTN', '64', 'BT', 'BT', 'Bhutan'),
    (100, 'BU', 'Bulgaria', 'BG', 'BGR', '100', 'BU', 'BG', 'Bulgaria'),
    (74, 'BV', 'Bouvet Island', 'BV', 'BVT', '74', 'BV', 'BV', 'Bouvet Island'),
    (96, 'BX', 'Brunei', 'BN', 'BRN', '96', 'BX', 'BN', 'Brunei'),
    (108, 'BY', 'Burundi', 'BI', 'BDI', '108', 'BY', 'BI', 'Burundi'),
    (124, 'CA', 'Canada', 'CA', 'CAN', '124', 'CA', 'CA', 'Canada'),
    (116, 'CB', 'Cambodia', 'KH', 'KHM', '116', 'CB', 'KH', 'Cambodia'),
    (148, 'CD', 'Chad', 'TD', 'TCD', '148', 'CD', 'TD', 'Chad'),
    (144, 'CE', 'Sri Lanka', 'LK', 'LKA', '144', 'CE', 'LK', 'Sri Lanka'),
    (178, 'CF', 'Congo', 'CG', 'COG', '178', 'CF', 'CG', 'Congo'),
    (180, 'CG', 'Democratic Republic of Congo', 'CD', 'COD', '180', 'CG', 'CD', 'Democratic Republic of Congo'),
    (156, 'CH', 'China', 'CN', 'CHN', '156', 'CH', 'CN', 'China'),
    (152, 'CI', 'Chile', 'CL', 'CHL', '152', 'CI', 'CL', 'Chile'),
    (136, 'CJ', 'Cayman Islands', 'KY', 'CYM', '136', 'CJ', 'CB', 'Caribbean'),
    (166, 'CK', 'Cocos (Keeling) Islands', 'CC', 'CCK', '166', 'CK', 'CC', 'Cocos (Keeling) Islands'),
    (120, 'CM', 'Cameroon', 'CM', 'CMR', '120', 'CM', 'CM', 'Cameroon'),
    (174, 'CN', 'Comoros', 'KM', 'COM', '174', 'CN', 'KM', 'Comoros'),
    (170, 'CO', 'Colombia', 'CO', 'COL', '170', 'CO', 'CO', 'Colombia'),
    (580, 'CQ', 'Northern Mariana Islands', 'MP', 'MNP', '580', 'CQ', 'GU', 'Guam'),
    (996, 'CR', 'Coral Sea Islands', 'CW', '', '996', 'CR', '', 'Coral Sea Islands'),
    (188, 'CS', 'Costa Rica', 'CR', 'CRI', '188', 'CS', 'CR', 'Costa Rica'),
    (140, 'CT', 'Central African Republic', 'CF', 'CAF', '140', 'CT', 'CF', 'Central African Republic'),
    (192, 'CU', 'Cuba', 'CU', 'CUB', '192', 'CU', 'CB', 'Caribbean'),
    (132, 'CV', 'Cape Verde', 'CV', 'CPV', '132', 'CV', 'CV', 'Cape Verde'),
    (184, 'CW', 'Cook Islands', 'CK', 'COK', '184', 'CW', 'CK', 'Cook Islands'),
    (208, 'DA', 'Denmark', 'DK', 'DNK', '208', 'DA', 'DK', 'Denmark'),
    (262, 'DJ', 'Djibouti', 'DJ', 'DJI', '262', 'DJ', 'DJ', 'Djibouti'),
    (212, 'DO', 'Dominica', 'DM', 'DMA', '212', 'DO', 'CB', 'Caribbean'),
    (985, 'DQ', 'Jarvis Island', '', '', '985', 'DQ', '', 'Jarvis Island'),
    (214, 'DR', 'Dominican Republic', 'DO', 'DOM', '214', 'DR', 'CB', 'Caribbean'),
    (218, 'EC', 'Ecuador', 'EC', 'ECU', '218', 'EC', 'EC', 'Ecuador'),
    (818, 'EG', 'Egypt', 'EG', 'EGY', '818', 'EG', 'EG', 'Egypt'),
    (372, 'EI', 'Ireland', 'IE', 'IRL', '372', 'EI', 'IE', 'Ireland'),
    (226, 'EK', 'Equatorial Guinea', 'GQ', 'GNQ', '226', 'EK', 'GQ', 'Equatorial Guinea'),
    (233, 'EN', 'Estonia', 'EE', 'EST', '233', 'EN', 'EE', 'Estonia'),
    (232, 'ER', 'Eritrea', 'ER', 'ERI', '232', 'ER', 'ER', 'Eritrea'),
    (222, 'ES', 'El Salvador', 'SV', 'SLV', '222', 'ES', 'SV', 'El Salvador'),
    (231, 'ET', 'Ethiopia', 'ET', 'ETH', '231', 'ET', 'ET', 'Ethiopia'),
    (992, 'EU', 'Europa Island', '', '', '992', 'EU', '', 'Europa Island'),
    (203, 'EZ', 'Czech Republic', 'CZ', 'CZE', '203', 'EZ', 'CZ', 'Czech Republic'),
    (254, 'FG', 'French Guyana', 'GF', 'GUF', '254', 'FG', 'GF', 'French Guyana'),
    (246, 'FI', 'Finland', 'FI', 'FIN', '246', 'FI', 'FI', 'Finland'),
    (242, 'FJ', 'Fiji', 'FJ', 'FJI', '242', 'FJ', 'FJ', 'Fiji'),
    (238, 'FK', 'Falkland Islands', 'FK', 'FLK', '238', 'FK', 'FK', 'Falkland Islands'),
    (583, 'FM', 'Federated States of Micronesia', 'FM', 'FSM', '583', 'FM', 'FM', 'Federated States of Micronesia'),
    (234, 'FO', 'Faroe Islands', 'FO', 'FRO', '234', 'FO', 'FO', 'Faroe Islands'),
    (258, 'FP', 'French Polynesia', 'PF', 'PYF', '258', 'FP', 'PF', 'French Polynesia'),
    (999, 'FQ', 'Baker Island', '', '', '999', 'FQ', '', 'Baker Island'),
    (250, 'FR', 'France', 'FR', 'FRA', '250', 'FR', 'FR', 'France'),
    (260, 'FS', 'French Southern and Antarctic Lands', 'TF', '', '260', 'FS', 'TF', 'French Southern and Antarctic Lands'),
    (270, 'GA', 'Gambia', 'GM', 'GMB', '270', 'GA', 'GM', 'Gambia'),
    (266, 'GB', 'Gabon', 'GA', 'GAB', '266', 'GB', 'GA', 'Gabon'),
    (268, 'GG', 'Georgia', 'GE', 'GEO', '268', 'GG', 'GE', 'Georgia'),
    (288, 'GH', 'Ghana', 'GH', 'GHA', '288', 'GH', 'GH', 'Ghana'),
    (292, 'GI', 'Gibraltar', 'GI', 'GIB', '292', 'GI', 'GI', 'Gibraltar'),
    (308, 'GJ', 'Grenada', 'GD', 'GRD', '308', 'GJ', 'CB', 'Caribbean'),
    (831, 'GK', 'Guernsey', 'GG', 'GGY', '831', 'GK', 'GB', 'United Kingdom'),
    (304, 'GL', 'Greenland', 'GL', 'GRL', '304', 'GL', 'GL', 'Greenland'),
    (276, 'GM', 'Germany', 'DE', 'DEU', '276', 'GM', 'DE', 'Germany'),
    (990, 'GO', 'Glorioso Islands', '', '', '990', 'GO', '', 'Glorioso Islands'),
    (312, 'GP', 'Guadeloupe', 'GP', 'GLP', '312', 'GP', 'CB', 'Caribbean'),
    (316, 'GQ', 'Guam', 'GU', 'GUM', '316', 'GQ', 'GU', 'Guam'),
    (300, 'GR', 'Greece', 'GR', 'GRC', '300', 'GR', 'GR', 'Greece'),
    (320, 'GT', 'Guatemala', 'GT', 'GTM', '320', 'GT', 'GT', 'Guatemala'),
    (324, 'GV', 'Guinea', 'GN', 'GIN', '324', 'GV', 'GN', 'Guinea'),
    (328, 'GY', 'Guyana', 'GY', 'GUY', '328', 'GY', 'GY', 'Guyana'),
    (991, 'GZ', 'Gaza Strip', '', '', '991', 'GZ', 'IL', 'Israel'),
    (332, 'HA', 'Haiti', 'HT', 'HTI', '332', 'HA', 'CB', 'Caribbean'),
    (344, 'HK', 'Hong Kong', 'HK', 'HKG', '344', 'HK', 'HK', 'Hong Kong'),
    (334, 'HM', 'Heard Island and McDonald Isles', 'HM', 'HMD', '334', 'HM', 'HM', 'Heard Island and McDonald Isles'),
    (340, 'HO', 'Honduras', 'HN', 'HND', '340', 'HO', 'HN', 'Honduras'),
    (988, 'HQ', 'Howland Island', '', '', '988', 'HQ', '', 'Howland Island'),
    (191, 'HR', 'Croatia', 'HR', 'HRV', '191', 'HR', 'HR', 'Croatia'),
    (348, 'HU', 'Hungary', 'HU', 'HUN', '348', 'HU', 'HU', 'Hungary'),
    (352, 'IC', 'Iceland', 'IS', 'ISL', '352', 'IC', 'IS', 'Iceland'),
    (360, 'ID', 'Indonesia', 'ID', 'IDN', '360', 'ID', 'ID', 'Indonesia'),
    (833, 'IM', 'Isle of Man', 'IM', 'IMN', '833', 'IM', 'GB', 'United Kingdom'),
    (356, 'IN', 'India', 'IN', 'IND', '356', 'IN', 'IN', 'India'),
    (86, 'IO', 'British Indian Ocean Territory', 'IO', 'IOT', '86', 'IO', 'IO', 'British Indian Ocean Territory'),
    (997, 'IP', 'Clipperton Island', '', '', '997', 'IP', '', 'Clipperton Island'),
    (364, 'IR', 'Iran', 'IR', 'IRN', '364', 'IR', 'IR', 'Iran'),
    (376, 'IS', 'Israel', 'IL', 'ISR', '376', 'IS', 'IL', 'Israel'),
    (380, 'IT', 'Italy', 'IT', 'ITA', '380', 'IT', 'IT', 'Italy'),
    (384, 'IV', 'Ivory Coast', 'CI', 'CIV', '384', 'IV', 'CI', 'Ivory Coast'),
    (368, 'IZ', 'Iraq', 'IQ', 'IRQ', '368', 'IZ', 'IQ', 'Iraq'),
    (392, 'JA', 'Japan', 'JP', 'JPN', '392', 'JA', 'JP', 'Japan'),
    (832, 'JE', 'Jersey', 'JE', 'JEY', '832', 'JE', 'GB', 'United Kingdom'),
    (388, 'JM', 'Jamaica', 'JM', 'JAM', '388', 'JM', 'CB', 'Caribbean'),
    (986, 'JN', 'Jan Mayen', '', '', '986', 'JN', '', 'Jan Mayen'),
    (400, 'JO', 'Jordan', 'JO', 'JOR', '400', 'JO', 'JO', 'Jordan'),
    (984, 'JQ', 'Johnston Atoll', '', '', '984', 'JQ', '', 'Johnston Atoll'),
    (983, 'JU', 'Juan de Nova Island', '', '', '983', 'JU', '', 'Juan de Nova Island'),
    (404, 'KE', 'Kenya', 'KE', 'KEN', '404', 'KE', 'KE', 'Kenya'),
    (417, 'KG', 'Kyrgyzstan', 'KG', 'KGZ', '417', 'KG', 'KG', 'Kyrgyzstan'),
    (408, 'KN', 'North Korea', 'KP', 'PRK', '408', 'KN', 'KP', 'North Korea'),
    (982, 'KQ', 'Kingman Reef', '', '', '982', 'KQ', '', 'Kingman Reef'),
    (296, 'KR', 'Kiribati', 'KI', 'KIR', '296', 'KR', 'KI', 'Kiribati'),
    (410, 'KS', 'South Korea', 'KR', 'KOR', '410', 'KS', 'KR', 'South Korea'),
    (162, 'KT', 'Christmas Island', 'CX', 'CXR', '162', 'KT', 'CX', 'Christmas Island'),
    (414, 'KU', 'Kuwait', 'KW', 'KWT', '414', 'KU', 'KW', 'Kuwait'),
    (398, 'KZ', 'Kazakhstan', 'KZ', 'KAZ', '398', 'KZ', 'KZ', 'Kazakhstan'),
    (418, 'LA', 'Laos', 'LA', 'LAO', '418', 'LA', 'LA', 'Laos'),
    (422, 'LE', 'Lebanon', 'LB', 'LBN', '422', 'LE', 'LB', 'Lebanon'),
    (428, 'LG', 'Latvia', 'LV', 'LVA', '428', 'LG', 'LV', 'Latvia'),
    (440, 'LH', 'Lithuania', 'LT', 'LTU', '440', 'LH', 'LT', 'Lithuania'),
    (430, 'LI', 'Liberia', 'LR', 'LBR', '430', 'LI', 'LR', 'Liberia'),
    (703, 'LO', 'Slovakia', 'SK', 'SVK', '703', 'LO', 'SK', 'Slovakia'),
    (979, 'LQ', 'Palmyra Atoll', '', '', '979', 'LQ', '', 'Palmyra Atoll'),
    (438, 'LS', 'Liechtenstein', 'LI', 'LIE', '438', 'LS', 'LI', 'Liechtenstein'),
    (426, 'LT', 'Lesotho', 'LS', 'LSO', '426', 'LT', 'LS', 'Lesotho'),
    (442, 'LU', 'Luxembourg', 'LU', 'LUX', '442', 'LU', 'LU', 'Luxembourg'),
    (434, 'LY', 'Libya', 'LY', 'LBY', '434', 'LY', 'LY', 'Libya'),
    (450, 'MA', 'Madagascar', 'MG', 'MDG', '450', 'MA', 'MG', 'Madagascar'),
    (474, 'MB', 'Martinique', 'MQ', 'MTQ', '474', 'MB', 'CB', 'Caribbean'),
    (498, 'MD', 'Moldova', 'MD', 'MDA', '498', 'MD', 'MD', 'Moldova'),
    (175, 'MF', 'Mayotte', 'YT', '', '175', 'MF', 'YT', 'Mayotte'),
    (496, 'MG', 'Mongolia', 'MN', 'MNG', '496', 'MG', 'MN', 'Mongolia'),
    (500, 'MH', 'Montserrat', 'MS', 'MSR', '500', 'MH', 'CB', 'Caribbean'),
    (454, 'MI', 'Malawi', 'MW', 'MWI', '454', 'MI', 'MW', 'Malawi'),
    (499, 'MJ', 'Montenegro', 'ME', 'MNE', '499', 'MJ', 'CS', 'Montenegro'),
    (807, 'MK', 'Macedonia', 'MK', 'MKD', '807', 'MK', 'MK', 'Macedonia'),
    (466, 'ML', 'Mali', 'ML', 'MLI', '466', 'ML', 'ML', 'Mali'),
    (492, 'MN', 'Monaco', 'MC', 'MCO', '492', 'MN', 'FR', 'France'),
    (504, 'MO', 'Morocco', 'MA', 'MAR', '504', 'MO', 'MA', 'Morocco'),
    (480, 'MP', 'Mauritius', 'MU', 'MUS', '480', 'MP', 'MU', 'Mauritius'),
    (981, 'MQ', 'Midway Islands', '', '', '981', 'MQ', '', 'Midway Islands'),
    (478, 'MR', 'Mauritania', 'MR', 'MRT', '478', 'MR', 'MR', 'Mauritania'),
    (470, 'MT', 'Malta', 'MT', 'MLT', '470', 'MT', 'MT', 'Malta'),
    (512, 'MU', 'Oman', 'OM', 'OMN', '512', 'MU', 'OM', 'Oman'),
    (462, 'MV', 'Maldives', 'MV', 'MDV', '462', 'MV', 'MV', 'Maldives'),
    (484, 'MX', 'Mexico', 'MX', 'MEX', '484', 'MX', 'MX', 'Mexico'),
    (458, 'MY', 'Malaysia', 'MY', 'MYS', '458', 'MY', 'MY', 'Malaysia'),
    (508, 'MZ', 'Mozambique', 'MZ', 'MOZ', '508', 'MZ', 'MZ', 'Mozambique'),
    (540, 'NC', 'New Caledonia', 'NC', 'NCL', '540', 'NC', 'NC', 'New Caledonia'),
    (570, 'NE', 'Niue', 'NU', 'NIU', '570', 'NE', 'NU', 'Niue'),
    (574, 'NF', 'Norfolk Island', 'NF', 'NFK', '574', 'NF', 'NF', 'Norfolk Island'),
    (562, 'NG', 'Niger', 'NE', 'NER', '562', 'NG', 'NE', 'Niger'),
    (548, 'NH', 'Vanuatu', 'VU', 'VUT', '548', 'NH', 'VU', 'Vanuatu'),
    (566, 'NI', 'Nigeria', 'NG', 'NGA', '566', 'NI', 'NG', 'Nigeria'),
    (528, 'NL', 'Netherlands', 'NL', 'NLD', '528', 'NL', 'NL', 'Netherlands'),
    (578, 'NO', 'Norway', 'NO', 'NOR', '578', 'NO', 'NO', 'Norway'),
    (524, 'NP', 'Nepal', 'NP', 'NPL', '524', 'NP', 'NP', 'Nepal'),
    (520, 'NR', 'Nauru', 'NR', 'NRU', '520', 'NR', 'NR', 'Nauru'),
    (740, 'NS', 'Suriname', 'SR', 'SUR', '740', 'NS', 'SR', 'Suriname'),
    (558, 'NU', 'Nicaragua', 'NI', 'NIC', '558', 'NU', 'NI', 'Nicaragua'),
    (554, 'NZ', 'New Zealand', 'NZ', 'NZL', '554', 'NZ', 'NZ', 'New Zealand'),
    (600, 'PA', 'Paraguay', 'PY', 'PRY', '600', 'PA', 'PY', 'Paraguay'),
    (612, 'PC', 'Pitcairn Islands', 'PN', 'PCN', '612', 'PC', 'PN', 'Pitcairn Islands'),
    (604, 'PE', 'Peru', 'PE', 'PER', '604', 'PE', 'PE', 'Peru'),
    (978, 'PF', 'Paracel Islands', '', '', '978', 'PF', '', 'Paracel Islands'),
    (976, 'PG', 'Spratly Islands', '', '', '976', 'PG', '', 'Spratly Islands'),
    (586, 'PK', 'Pakistan', 'PK', 'PAK', '586', 'PK', 'PK', 'Pakistan'),
    (616, 'PL', 'Poland', 'PL', 'POL', '616', 'PL', 'PL', 'Poland'),
    (591, 'PM', 'Panama', 'PA', 'PAN', '591', 'PM', 'PA', 'Panama'),
    (620, 'PO', 'Portugal', 'PT', 'PRT', '620', 'PO', 'PT', 'Portugal'),
    (598, 'PP', 'Papua New Guinea', 'PG', 'PNG', '598', 'PP', 'PG', 'Papua New Guinea'),
    (585, 'PS', 'Palau', 'PW', 'PLW', '585', 'PS', 'PW', 'Palau'),
    (624, 'PU', 'Guinea-Bissau', 'GW', 'GNB', '624', 'PU', 'GW', 'Guinea-Bissau'),
    (634, 'QA', 'Qatar', 'QA', 'QAT', '634', 'QA', 'QA', 'Qatar'),
    (688, 'RB', 'Serbia', 'RS', 'SRB', '688', 'RB', 'CS', 'Serbia'),
    (638, 'RE', 'Reunion', 'RE', 'REU', '638', 'RE', 'RE', 'Reunion'),
    (584, 'RM', 'Marshall Islands', 'MH', 'MHL', '584', 'RM', 'MH', 'Marshall Islands'),
    (663, 'RN', 'Saint Martin', 'MF', 'MAF', '663', 'RN', 'CB', 'Caribbean'),
    (642, 'RO', 'Romania', 'RO', 'ROU', '642', 'RO', 'RO', 'Romania'),
    (608, 'RP', 'Philippines', 'PH', 'PHL', '608', 'RP', 'PH', 'Philippines'),
    (630, 'RQ', 'Puerto Rico', 'PR', 'PRI', '630', 'RQ', 'CB', 'Caribbean'),
    (643, 'RS', 'Russia', 'RU', 'RUS', '643', 'RS', 'RU', 'Russia'),
    (646, 'RW', 'Rwanda', 'RW', 'RWA', '646', 'RW', 'RW', 'Rwanda'),
    (682, 'SA', 'Saudi Arabia', 'SA', 'SAU', '682', 'SA', 'SA', 'Saudi Arabia'),
    (666, 'SB', 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', 'SB', 'PM', 'Saint Pierre and Miquelon'),
    (659, 'SC', 'St Kitts and Nevis', 'KN', 'KNA', '659', 'SC', 'CB', 'Caribbean'),
    (690, 'SE', 'Seychelles', 'SC', 'SYC', '690', 'SE', 'SC', 'Seychelles'),
    (710, 'SF', 'South Africa', 'ZA', 'ZAF', '710', 'SF', 'ZA', 'South Africa'),
    (686, 'SG', 'Senegal', 'SN', 'SEN', '686', 'SG', 'SN', 'Senegal'),
    (654, 'SH', 'Saint Helena and Dependencies', 'SH', 'SHN', '654', 'SH', 'SH', 'Saint Helena and Dependencies'),
    (705, 'SI', 'Slovenia', 'SI', 'SVN', '705', 'SI', 'SI', 'Slovenia'),
    (694, 'SL', 'Sierra Leone', 'SL', 'SLE', '694', 'SL', 'SL', 'Sierra Leone'),
    (674, 'SM', 'San Marino', 'SM', 'SMR', '674', 'SM', 'IT', 'Italy'),
    (702, 'SN', 'Singapore', 'SG', 'SGP', '702', 'SN', 'SG', 'Singapore'),
    (706, 'SO', 'Somalia', 'SO', 'SOM', '706', 'SO', 'SO', 'Somalia'),
    (724, 'SP', 'Spain', 'ES', 'ESP', '724', 'SP', 'ES', 'Spain'),
    (662, 'ST', 'Saint Lucia', 'LC', 'LCA', '662', 'ST', 'CB', 'Caribbean'),
    (736, 'SU', 'Sudan', 'SD', 'SDN', '736', 'SU', 'SD', 'Sudan'),
    (744, 'SV', 'Svalbard', 'SJ', 'SJM', '744', 'SV', 'SJ', 'Svalbard'),
    (752, 'SW', 'Sweden', 'SE', 'SWE', '752', 'SW', 'SE', 'Sweden'),
    (239, 'SX', 'South Georgia and South Sandwich Islands', 'GS', 'SGS', '239', 'SX', 'GS', 'South Georgia and South Sandwich Islands'),
    (760, 'SY', 'Syria', 'SY', 'SYR', '760', 'SY', 'SY', 'Syria'),
    (756, 'SZ', 'Switzerland', 'CH', 'CHE', '756', 'SZ', 'CH', 'Switzerland'),
    (652, 'TB', 'Saint Barthelemy', 'BL', 'BLM', '652', 'TB', 'CB', 'Caribbean'),
    (780, 'TD', 'Trinidad and Tobago', 'TT', 'TTO', '780', 'TD', 'CB', 'Caribbean'),
    (974, 'TE', 'Tromelin Island', '', '', '974', 'TE', '', 'Tromelin Island'),
    (764, 'TH', 'Thailand', 'TH', 'THA', '764', 'TH', 'TH', 'Thailand'),
    (762, 'TI', 'Tajikistan', 'TJ', 'TJK', '762', 'TI', 'TJ', 'Tajikistan'),
    (796, 'TK', 'Turks And Caicos Islands', 'TC', 'TCA', '796', 'TK', 'CB', 'Caribbean'),
    (772, 'TL', 'Tokelau', 'TK', 'TKL', '772', 'TL', 'TK', 'Tokelau'),
    (776, 'TN', 'Tonga', 'TO', 'TON', '776', 'TN', 'TO', 'Tonga'),
    (768, 'TO', 'Togo', 'TG', 'TGO', '768', 'TO', 'TG', 'Togo'),
    (678, 'TP', 'Sao Tome and Principe', 'ST', 'STP', '678', 'TP', 'ST', 'Sao Tome and Principe'),
    (788, 'TS', 'Tunisia', 'TN', 'TUN', '788', 'TS', 'TN', 'Tunisia'),
    (626, 'TT', 'East Timor', 'TL', 'TLS', '626', 'TT', 'ID', 'Indonesia'),
    (792, 'TU', 'Turkey', 'TR', 'TUR', '792', 'TU', 'TR', 'Turkey'),
    (798, 'TV', 'Tuvalu', 'TV', 'TUV', '798', 'TV', 'TV', 'Tuvalu'),
    (158, 'TW', 'Taiwan', 'TW', 'TWN', '158', 'TW', 'TW', 'Taiwan'),
    (795, 'TX', 'Turkmenistan', 'TM', 'TKM', '795', 'TX', 'TM', 'Turkmenistan'),
    (834, 'TZ', 'Tanzania', 'TZ', 'TZA', '834', 'TZ', 'TZ', 'Tanzania'),
    (800, 'UG', 'Uganda', 'UG', 'UGA', '800', 'UG', 'UG', 'Uganda'),
    (826, 'UK', 'United Kingdom', 'GB', 'GBR', '826', 'UK', 'GB', 'United Kingdom'),
    (804, 'UP', 'Ukraine', 'UA', 'UKR', '804', 'UP', 'UA', 'Ukraine'),
    (840, 'US', 'United States', 'US', 'USA', '840', 'US', 'US', 'United States'),
    (854, 'UV', 'Burkina Faso', 'BF', 'BFA', '854', 'UV', 'BF', 'Burkina Faso'),
    (858, 'UY', 'Uruguay', 'UY', 'URY', '858', 'UY', 'UY', 'Uruguay'),
    (860, 'UZ', 'Uzbekistan', 'UZ', 'UZB', '860', 'UZ', 'UZ', 'Uzbekistan'),
    (670, 'VC', 'Saint Vincent and The Grenadines', 'VC', 'VCT', '670', 'VC', 'CB', 'Caribbean'),
    (862, 'VE', 'Venezuela', 'VE', 'VEN', '862', 'VE', 'VE', 'Venezuela'),
    (92, 'VI', 'British Virgin Islands', 'VG', 'VGB', '92', 'VI', 'CB', 'Caribbean'),
    (704, 'VM', 'Vietnam', 'VN', 'VNM', '704', 'VM', 'VN', 'Vietnam'),
    (850, 'VQ', 'U.S. Virgin Islands', 'VI', 'VIR', '850', 'VQ', 'CB', 'Caribbean'),
    (336, 'VT', 'Vatican City', 'VA', 'VAT', '336', 'VT', 'IT', 'Italy'),
    (951, 'W1', 'Offshore US Gulf of Mexico', 'W1', 'W1', '951', 'W1', '', 'Offshore US Gulf of Mexico'),
    (950, 'W3', 'Offshore Northern Europe', 'W3', 'W3', '950', 'W3', '', 'Offshore Northern Europe'),
    (516, 'WA', 'Namibia', 'NA', 'NAM', '516', 'WA', 'NA', 'Namibia'),
    (971, 'WE', 'West Bank', '', 'PSE', '971', 'WE', 'IL', 'Israel'),
    (876, 'WF', 'Wallis and Futuna', 'WF', 'WLF', '876', 'WF', 'WF', 'Wallis and Futuna'),
    (732, 'WI', 'Western Sahara', 'EH', 'ESH', '732', 'WI', 'EH', 'Western Sahara'),
    (972, 'WQ', 'Wake Island', '', '', '972', 'WQ', '', 'Wake Island'),
    (882, 'WS', 'Samoa', 'WS', 'WSM', '882', 'WS', 'WS', 'Samoa'),
    (748, 'WZ', 'Swaziland', 'SZ', 'SWZ', '748', 'WZ', 'SZ', 'Swaziland'),
    (196, 'XA', 'Cyprus', 'CY', 'CYP', '196', 'XA', 'CY', 'Cyprus'),
    (994, 'XB', 'Cyprus', 'CY', 'CYP', '994', 'XB', 'CY', 'Cyprus'),
    (989, 'XC', 'Golan Heights', '', '', '989', 'XC', 'IL', 'Israel'),
    (534, 'XJ', 'Sint Maarten', 'XJ', 'XJJ', '534', 'XJ', 'CB', 'Caribbean'),
    (975, 'XK', 'St. Eustatius', 'XK', 'XKK', '975', 'XK', 'CB', 'Caribbean'),
    (960, 'XL', 'Saba', 'FX', 'FXX', '960', 'XL', 'CB', 'Caribbean'),
    (531, 'XM', 'Curacao', 'XM', 'XMM', '531', 'XM', 'CB', 'Caribbean'),
    (970, 'XN', 'Bonaire', 'CS', 'SCG', '970', 'XN', 'CB', 'Caribbean'),
    (887, 'YM', 'Yemen', 'YE', 'YEM', '887', 'YM', 'YE', 'Yemen'),
    (894, 'ZA', 'Zambia', 'ZM', 'ZMB', '894', 'ZA', 'ZM', 'Zambia'),
    (716, 'ZI', 'Zimbabwe', 'ZW', 'ZWE', '716', 'ZI', 'ZW', 'Zimbabwe'),
    (0, 'ZZ', 'Unknown', '', '', '', '', 'ZZ', 'Unknown')
