INSERT INTO REF.Construction (constructionschemeName, constructionCode, constructionName, constructionBandName) VALUES
('ATC','0','Unknown','UNKNOWN'),
('ATC','1','Wood Frame','UNKNOWN'),
('ATC','2','Light Metal','UNKNOWN'),
('ATC','3','Unreinforced Masonry Wall','UNKNOWN'),
('ATC','4','URM Wall with Frame','UNKNOWN'),
('ATC','5','RC Shear Wall with Frame','UNKNOWN'),
('ATC','6','RC Shear Wall without Frame','UNKNOWN'),
('ATC','7','RM Shear Wall','UNKNOWN'),
('ATC','8','RM Shear Wall with Frame','UNKNOWN'),
('ATC','9','Braced Steel Frame','UNKNOWN'),
('ATC','10','Moment Steel Frame (Perimeter)','UNKNOWN'),
('ATC','11','Moment Steel Frame (Distributed)','UNKNOWN'),
('ATC','12','Ductile RC Frame (Distributed)','UNKNOWN'),
('ATC','13','Non-Ductile RC Frame (Distributed)','UNKNOWN'),
('ATC','14','Precast Concrete (Non Tilt-Up)','UNKNOWN'),
('ATC','15','Long Span','UNKNOWN'),
('ATC','16','Tilt-Up','UNKNOWN'),
('ATC','17','Mobile Home','UNKNOWN'),
('ATC','19','Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans','UNKNOWN'),
('ATC','20','Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans','UNKNOWN'),
('ATC','21','Major Bridges (> 500 ft. spans)','UNKNOWN'),
('ATC','22','Pipelines - Underground','UNKNOWN'),
('ATC','23','Pipelines - At Grade','UNKNOWN'),
('ATC','24','Concrete Dams','UNKNOWN'),
('ATC','25','Earthfill and Rockfill Dams','UNKNOWN'),
('ATC','26','Alluvium Tunnels','UNKNOWN'),
('ATC','27','Rock Tunnels','UNKNOWN'),
('ATC','28','Cut & Cover Tunnels','UNKNOWN'),
('ATC','29','Storage Tank - Liquid - Underground','UNKNOWN'),
('ATC','30','Storage Tank - Solids - Underground','UNKNOWN'),
('ATC','31','Storage Tank - Liquid - On Ground','UNKNOWN'),
('ATC','32','Storage Tank - Solids - On Ground','UNKNOWN'),
('ATC','33','Storage Tank - Liquid - Elevated','UNKNOWN'),
('ATC','34','Storage Tank - Solids - Elevated','UNKNOWN'),
('ATC','35','Railroads (Track & Bed)','UNKNOWN'),
('ATC','36','Highways','UNKNOWN'),
('ATC','37','Runways','UNKNOWN'),
('ATC','38','High Industrial Masonry Chimneys','UNKNOWN'),
('ATC','39','High Industrial Concrete Chimneys','UNKNOWN'),
('ATC','40','High Industrial Steel Chimneys','UNKNOWN'),
('ATC','41','Cranes','UNKNOWN'),
('ATC','42','Conveyor Systems','UNKNOWN'),
('ATC','43','Conventional (< 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('ATC','44','Major (> 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('ATC','45','Broadcast Towers','UNKNOWN'),
('ATC','46','Observation Towers','UNKNOWN'),
('ATC','47','Offshore Towers','UNKNOWN'),
('ATC','48','Canals','UNKNOWN'),
('ATC','49','Earth Retaining Structures (> 20 ft. high)','UNKNOWN'),
('ATC','50','Waterfront Structures','UNKNOWN'),
('ATC','51','Residential Equipment','UNKNOWN'),
('ATC','52','Office Equipment','UNKNOWN'),
('ATC','53','Electrical Equipment','UNKNOWN'),
('ATC','54','Mechanical Equipment','UNKNOWN'),
('ATC','55','High Technology/Lab Equipment','UNKNOWN'),
('ATC','56','Trains, Trucks, Airplanes','UNKNOWN'),
('FIRE','0','Unknown','UNKNOWN'),
('FIRE','1','Frame','UNKNOWN'),
('FIRE','2','Joisted Masonry','UNKNOWN'),
('FIRE','3','Non-Combustile','UNKNOWN'),
('FIRE','4','Masonry Non-Combustile','UNKNOWN'),
('FIRE','5','Modified Fire Resistive','UNKNOWN'),
('FIRE','6','Fire Resistive','UNKNOWN'),
('FIRE','7','Heavy Timber Joisted Masonry','UNKNOWN'),
('FIRE','8','Superior Non-Combustible','UNKNOWN'),
('FIRE','9','Superior Masonry Non-Combustible','UNKNOWN'),
('FIRE','10','Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans','UNKNOWN'),
('FIRE','11','Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans','UNKNOWN'),
('FIRE','12','Major Bridges (> 500 ft. spans)','UNKNOWN'),
('FIRE','13','Pipelines - Underground','UNKNOWN'),
('FIRE','14','Pipelines - At Grade','UNKNOWN'),
('FIRE','15','Concrete Dams','UNKNOWN'),
('FIRE','16','Earthfill and Rockfill Dams','UNKNOWN'),
('FIRE','17','Alluvium Tunnels','UNKNOWN'),
('FIRE','18','Rock Tunnels','UNKNOWN'),
('FIRE','19','Cut & Cover Tunnels','UNKNOWN'),
('FIRE','20','Storage Tank - Liquid - Underground','UNKNOWN'),
('FIRE','21','Storage Tank - Solids - Underground','UNKNOWN'),
('FIRE','22','Storage Tank - Liquid - On Ground','UNKNOWN'),
('FIRE','23','Storage Tank - Solids - On Ground','UNKNOWN'),
('FIRE','24','Storage Tank - Liquid - Elevated','UNKNOWN'),
('FIRE','25','Storage Tank - Solids - Elevated','UNKNOWN'),
('FIRE','26','Railroads (Track & Bed)','UNKNOWN'),
('FIRE','27','Highways','UNKNOWN'),
('FIRE','28','Runways','UNKNOWN'),
('FIRE','29','High Industrial Masonry Chimneys','UNKNOWN'),
('FIRE','30','High Industrial Concrete Chimneys','UNKNOWN'),
('FIRE','31','High Industrial Steel Chimneys','UNKNOWN'),
('FIRE','32','Cranes','UNKNOWN'),
('FIRE','33','Conveyor Systems','UNKNOWN'),
('FIRE','34','Conventional (< 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('FIRE','35','Major (> 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('FIRE','36','Broadcast Towers','UNKNOWN'),
('FIRE','37','Observation Towers','UNKNOWN'),
('FIRE','38','Offshore Towers','UNKNOWN'),
('FIRE','39','Canals','UNKNOWN'),
('FIRE','40','Earth Retaining Structures (> 20 ft. high)','UNKNOWN'),
('FIRE','41','Waterfront Structures','UNKNOWN'),
('FIRE','42','Residential Equipment','UNKNOWN'),
('FIRE','43','Office Equipment','UNKNOWN'),
('FIRE','44','Electrical Equipment','UNKNOWN'),
('FIRE','45','Mechanical Equipment','UNKNOWN'),
('FIRE','46','High Technology/Lab Equipment','UNKNOWN'),
('FIRE','47','Trains, Trucks, Airplanes','UNKNOWN'),
('FIRE','48','PETROCHEMICAL FACILITIES','UNKNOWN'),
('FIRE','49','ELECTRIC POWER SYSTEMS','UNKNOWN'),
('FIRE','50','NATURAL GAS FACILITIES','UNKNOWN'),
('FIRE','51','PORT/HARBOR FACILITIES','UNKNOWN'),
('FIRE','52','HEAVY INDUSTRIAL FACILITIES','UNKNOWN'),
('FIRE','53','LIGHT INDUSTRIAL FACILITIES','UNKNOWN'),
('FIRE','48A','Oil Refineries & Petrochemical Plants','UNKNOWN'),
('FIRE','48B','Tank Farms','UNKNOWN'),
('FIRE','48C','Pumping Stations','UNKNOWN'),
('FIRE','48D','Pipelines - General','UNKNOWN'),
('FIRE','49A','Transmission/Distribution Substations','UNKNOWN'),
('FIRE','49B','Transmission/Distribution Lines','UNKNOWN'),
('FIRE','49C','Fossil Fuel Plants','UNKNOWN'),
('FIRE','49D','Cogeneration Plants','UNKNOWN'),
('FIRE','49E','Hydroelectric Plants','UNKNOWN'),
('FIRE','50A','Compressor Stations','UNKNOWN'),
('FIRE','50B','Pipelines - General','UNKNOWN'),
('FIRE','50C','Liquefied Natural Gas','UNKNOWN'),
('FIRE','51A','Waterfront Facilities','UNKNOWN'),
('FIRE','51B','Crane/Cargo Handling','UNKNOWN'),
('FIRE','51C','Fuel Facilities','UNKNOWN'),
('FIRE','52A','Pulp & Paper','UNKNOWN'),
('FIRE','52B','Steel Mill','UNKNOWN'),
('FIRE','52C','Mining','UNKNOWN'),
('FIRE','52D','Cement Mill','UNKNOWN'),
('FIRE','53A','High Technology','UNKNOWN'),
('FIRE','53B','Telecommunication','UNKNOWN'),
('ISO','0','Unknown','UNKNOWN'),
('ISO','1','Wood Frame - Small (1A,B,C)','UNKNOWN'),
('ISO','2','Wood Frame - Large (1D)','UNKNOWN'),
('ISO','3','All-Metal - Small (2A)','UNKNOWN'),
('ISO','4','All-Metal - Large (2B)','UNKNOWN'),
('ISO','5','Steel Frame - Sup. EQ Resistive (3A)','UNKNOWN'),
('ISO','6','Steel Frame - Ordinary (3B)','UNKNOWN'),
('ISO','7','Steel Frame - Other (3C)','UNKNOWN'),
('ISO','8','Reinforced Conc. - Sup. EQ Res. (4A)','UNKNOWN'),
('ISO','9','Reinforced Concrete - Ordinary (4B)','UNKNOWN'),
('ISO','10','Reinforced Concrete - Precast (4C)','UNKNOWN'),
('ISO','11','Reinforced Concrete - Other (4D)','UNKNOWN'),
('ISO','12','Mix Constr. - Sup. EQ Resistive (5A)','UNKNOWN'),
('ISO','13','Mix Constr. - Ordinary EQ Res. (5AA)','UNKNOWN'),
('ISO','14','Mix Constr. - Ord. Non-EQ Res. (5B)','UNKNOWN'),
('ISO','15','Mix Constr. - Hollow Masonry (5C)','UNKNOWN'),
('ISO','16','Earthquake Resistive (6)','UNKNOWN'),
('ISO','17','Mobile Home (1E)','UNKNOWN'),
('ISO','18','Specially Engineered Facility','UNKNOWN'),
('ISO','19','Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans','UNKNOWN'),
('ISO','20','Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans','UNKNOWN'),
('ISO','21','Major Bridges (> 500 ft. spans)','UNKNOWN'),
('ISO','22','Pipelines - Underground','UNKNOWN'),
('ISO','23','Pipelines - At Grade','UNKNOWN'),
('ISO','24','Concrete Dams','UNKNOWN'),
('ISO','25','Earthfill and Rockfill Dams','UNKNOWN'),
('ISO','26','Alluvium Tunnels','UNKNOWN'),
('ISO','27','Rock Tunnels','UNKNOWN'),
('ISO','28','Cut & Cover Tunnels','UNKNOWN'),
('ISO','29','Storage Tank - Liquid - Underground','UNKNOWN'),
('ISO','30','Storage Tank - Solids - Underground','UNKNOWN'),
('ISO','31','Storage Tank - Liquid - On Ground','UNKNOWN'),
('ISO','32','Storage Tank - Solids - On Ground','UNKNOWN'),
('ISO','33','Storage Tank - Liquid - Elevated','UNKNOWN'),
('ISO','34','Storage Tank - Solids - Elevated','UNKNOWN'),
('ISO','35','Railroads (Track & Bed)','UNKNOWN'),
('ISO','36','Highways','UNKNOWN'),
('ISO','37','Runways','UNKNOWN'),
('ISO','38','High Industrial Masonry Chimneys','UNKNOWN'),
('ISO','39','High Industrial Concrete Chimneys','UNKNOWN'),
('ISO','40','High Industrial Steel Chimneys','UNKNOWN'),
('ISO','41','Cranes','UNKNOWN'),
('ISO','42','Conveyor Systems','UNKNOWN'),
('ISO','43','Conventional (< 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('ISO','44','Major (> 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('ISO','45','Broadcast Towers','UNKNOWN'),
('ISO','46','Observation Towers','UNKNOWN'),
('ISO','47','Offshore Towers','UNKNOWN'),
('ISO','48','Canals','UNKNOWN'),
('ISO','49','Earth Retaining Structures (> 20 ft. high)','UNKNOWN'),
('ISO','50','Waterfront Structures','UNKNOWN'),
('ISO','51','Residential Equipment','UNKNOWN'),
('ISO','52','Office Equipment','UNKNOWN'),
('ISO','53','Electrical Equipment','UNKNOWN'),
('ISO','54','Mechanical Equipment','UNKNOWN'),
('ISO','55','High Technology/Lab Equipment','UNKNOWN'),
('ISO','56','Trains, Trucks, Airplanes','UNKNOWN'),
('ISO','57','PETROCHEMICAL FACILITIES','UNKNOWN'),
('ISO','58','ELECTRIC POWER SYSTEMS','UNKNOWN'),
('ISO','59','NATURAL GAS FACILITIES','UNKNOWN'),
('ISO','60','PORT/HARBOR FACILITIES','UNKNOWN'),
('ISO','61','HEAVY INDUSTRIAL FACILITIES','UNKNOWN'),
('ISO','62','LIGHT INDUSTRIAL FACILITIES','UNKNOWN'),
('ISO','57A','Oil Refineries & Petrochemical Plants','UNKNOWN'),
('ISO','57B','Tank Farms','UNKNOWN'),
('ISO','57C','Pumping Stations','UNKNOWN'),
('ISO','57D','Pipelines - General','UNKNOWN'),
('ISO','58A','Transmission/Distribution Substations','UNKNOWN'),
('ISO','58B','Transmission/Distribution Lines','UNKNOWN'),
('ISO','58C','Fossil Fuel Plants','UNKNOWN'),
('ISO','58D','Cogeneration Plants','UNKNOWN'),
('ISO','58E','Hydroelectric Plants','UNKNOWN'),
('ISO','59A','Compressor Stations','UNKNOWN'),
('ISO','59B','Pipelines - General','UNKNOWN'),
('ISO','59C','Liquefied Natural Gas','UNKNOWN'),
('ISO','60A','Waterfront Facilities','UNKNOWN'),
('ISO','60B','Crane/Cargo Handling','UNKNOWN'),
('ISO','60C','Fuel Facilities','UNKNOWN'),
('ISO','61A','Pulp & Paper','UNKNOWN'),
('ISO','61B','Steel Mill','UNKNOWN'),
('ISO','61C','Mining','UNKNOWN'),
('ISO','61D','Cement Mill','UNKNOWN'),
('ISO','62A','High Technology','UNKNOWN'),
('ISO','62B','Telecommunication','UNKNOWN'),
('JPBLDG','0','Unknown','UNKNOWN'),
('JPBLDG','1','General OCC Fire Class1 (Default CC: Steel Frame)','UNKNOWN'),
('JPBLDG','2','General OCC Fire Class2 (Default CC: Steel Frame)','UNKNOWN'),
('JPBLDG','3','General OCC Fire Class3 (Default CC: Wood)','UNKNOWN'),
('JPBLDG','4','Other than SP, 1, 2, 3; or general wood Frame','UNKNOWN'),
('JPBLDG','A','Res OCC Fire Class A (Default CC: RC)','UNKNOWN'),
('JPBLDG','B','Res OCC Fire Class B (Default CC: Steel Frame)','UNKNOWN'),
('JPBLDG','C','Res OCC Fire Class C (Default CC: Wood Frame)','UNKNOWN'),
('JPBLDG','D','Other than A, B, C; or general wood dwellings','UNKNOWN'),
('JPBLDG','SP','Reinforced Concrete, SRC','UNKNOWN'),
('JPBLDG2010','0','Unknown','UNKNOWN'),
('JPBLDG2010','1','General OCC Fire Class1 (Default CC: RC or SRC)','UNKNOWN'),
('JPBLDG2010','2','General OCC Fire Class2 (Default CC: Steel Frame)','UNKNOWN'),
('JPBLDG2010','3','General OCC Fire Class3 (Default CC: Wood)','UNKNOWN'),
('JPBLDG2010','H','Res OCC Fire Class H (Default CC: Wood Frame)','UNKNOWN'),
('JPBLDG2010','M','Res OCC Fire Class M (Default CC: RC)','UNKNOWN'),
('JPBLDG2010','T','Res OCC Fire Class T (Default CC: RC)','UNKNOWN'),
('USER','0','Unknown','UNKNOWN'),
('USER','1','Fire Resistive','UNKNOWN'),
('USER','2','Concrete','UNKNOWN'),
('USER','3','Steel','UNKNOWN'),
('USER','4','Masonry','UNKNOWN'),
('USER','5','Frame/Veneer','UNKNOWN'),
('USER','6','Frame','UNKNOWN'),
('USER','7','Conventional Bridges (< 500 ft. spans) w/ Multiple Simple Spans','UNKNOWN'),
('USER','8','Conventional Bridges (< 500 ft. spans) w/ Monolithic Spans','UNKNOWN'),
('USER','9','Major Bridges (> 500 ft. spans)','UNKNOWN'),
('USER','10','Pipelines - Underground','UNKNOWN'),
('USER','11','Pipelines - At Grade','UNKNOWN'),
('USER','12','Concrete Dams','UNKNOWN'),
('USER','13','Earthfill and Rockfill Dams','UNKNOWN'),
('USER','14','Alluvium Tunnels','UNKNOWN'),
('USER','15','Rock Tunnels','UNKNOWN'),
('USER','16','Cut & Cover Tunnels','UNKNOWN'),
('USER','17','Storage Tank - Liquid - Underground','UNKNOWN'),
('USER','18','Storage Tank - Solids - Underground','UNKNOWN'),
('USER','19','Storage Tank - Liquid - On Ground','UNKNOWN'),
('USER','20','Storage Tank - Solids - On Ground','UNKNOWN'),
('USER','21','Storage Tank - Liquid - Elevated','UNKNOWN'),
('USER','22','Storage Tank - Solids - Elevated','UNKNOWN'),
('USER','23','Railroads (Track & Bed)','UNKNOWN'),
('USER','24','Highways','UNKNOWN'),
('USER','25','Runways','UNKNOWN'),
('USER','26','High Industrial Masonry Chimneys','UNKNOWN'),
('USER','27','High Industrial Concrete Chimneys','UNKNOWN'),
('USER','28','High Industrial Steel Chimneys','UNKNOWN'),
('USER','29','Cranes','UNKNOWN'),
('USER','30','Conveyor Systems','UNKNOWN'),
('USER','31','Conventional (< 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('USER','32','Major (> 100 ft.) Electrical Transmission Line Towers','UNKNOWN'),
('USER','33','Broadcast Towers','UNKNOWN'),
('USER','34','Observation Towers','UNKNOWN'),
('USER','35','Offshore Towers','UNKNOWN'),
('USER','36','Canals','UNKNOWN'),
('USER','37','Earth Retaining Structures (> 20 ft. high)','UNKNOWN'),
('USER','38','Waterfront Structures','UNKNOWN'),
('USER','39','Residential Equipment','UNKNOWN'),
('USER','40','Office Equipment','UNKNOWN'),
('USER','41','Electrical Equipment','UNKNOWN'),
('USER','42','Mechanical Equipment','UNKNOWN'),
('USER','43','High Technology/Lab Equipment','UNKNOWN'),
('USER','44','Trains, Trucks, Airplanes','UNKNOWN')